### ISSUE TITLE
JMS: Review 4.1.0

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/gslab_python#135]
Hi Jesse,

We are about to release `gslab_python` and template v4.1.0. Release notes are [here for template](https://github.com/gslab-econ/template/pull/85#issuecomment-327258103) and [here for `gslab_python`](https://github.com/gslab-econ/gslab_python/pull/125#issuecomment-328713637). Please install `gslab_python` and clone template, each from the branch `4.1.0`. 

The task list was [here](https://github.com/gslab-econ/gslab_python/issues/101#issue-249128581). The original meeting notes are [here](https://github.com/gslab-econ/admin/issues/115#issue-247201402).

Please let me know if you have any questions. Thanks!

**Comment by jmshapir** [comment]
Started work on this. Installed ```gslab_python``` successfully in a virtualenv.

Three notes from this step:

1. Readme [here](https://github.com/gslab-econ/gslab_python/blob/4.1.0/README.md) still says 4.0.1 at the top.
2. I got an error from setup.py despite a clean install of site. I was able to move past this by  commenting out the relevant section of setup.py.
```
PS C:\Users\jshapir1\Downloads\pythontemp> env/Scripts/python env/Scripts/gslab_python-4.1.0/setup.py install clean
Traceback (most recent call last):
  File "env/Scripts/gslab_python-4.1.0/setup.py", line 25, in <module>
    package_locations = site.getsitepackages()
AttributeError: 'module' object has no attribute 'getsitepackages'
PS C:\Users\jshapir1\Downloads\pythontemp> env/Scripts/pip install site
Requirement already satisfied: site in c:\users\jshapir1\downloads\pythontemp\env\lib\site-packages
```
3. I had to upgrade my MS Visual C++ compiler. No big deal, just keeping track of things that I encountered.

**Comment by jmshapir** [comment]
I believe I've successfully installed ```gslab_python``` in my virtualenv:

```
~\Downloads\pythontemp> env/scripts/python env/Scripts/gslab_python-4.1.0/setup.py install clean
running install
running bdist_egg
running egg_info
creating GSLab_Tools.egg-info
writing requirements to GSLab_Tools.egg-info\requires.txt
writing GSLab_Tools.egg-info\PKG-INFO
writing top-level names to GSLab_Tools.egg-info\top_level.txt
writing dependency_links to GSLab_Tools.egg-info\dependency_links.txt
writing manifest file 'GSLab_Tools.egg-info\SOURCES.txt'
reading manifest file 'GSLab_Tools.egg-info\SOURCES.txt'
writing manifest file 'GSLab_Tools.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
warning: install_lib: 'build\lib' does not exist -- no Python modules to install

creating build
creating build\bdist.win32
creating build\bdist.win32\egg
creating build\bdist.win32\egg\EGG-INFO
copying GSLab_Tools.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying GSLab_Tools.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying GSLab_Tools.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
copying GSLab_Tools.egg-info\not-zip-safe -> build\bdist.win32\egg\EGG-INFO
copying GSLab_Tools.egg-info\requires.txt -> build\bdist.win32\egg\EGG-INFO
copying GSLab_Tools.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
creating dist
creating 'dist\GSLab_Tools-4.1.0-py2.7.egg' and adding 'build\bdist.win32\egg' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing GSLab_Tools-4.1.0-py2.7.egg
removing 'c:\users\jshapir1\downloads\pythontemp\env\lib\site-packages\GSLab_Tools-4.1.0-py2.7.egg' (and everything

creating c:\users\jshapir1\downloads\pythontemp\env\lib\site-packages\GSLab_Tools-4.1.0-py2.7.egg
Extracting GSLab_Tools-4.1.0-py2.7.egg to c:\users\jshapir1\downloads\pythontemp\env\lib\site-packages
GSLab-Tools 4.1.0 is already the active version in easy-install.pth

Installed c:\users\jshapir1\downloads\pythontemp\env\lib\site-packages\gslab_tools-4.1.0-py2.7.egg
Processing dependencies for GSLab-Tools==4.1.0
Searching for mmh3==2.4
Best match: mmh3 2.4
Processing mmh3-2.4-py2.7-win32.egg
mmh3 2.4 is already the active version in easy-install.pth

Using c:\users\jshapir1\downloads\pythontemp\env\lib\site-packages\mmh3-2.4-py2.7-win32.egg
Searching for scandir==1.5
Best match: scandir 1.5
Processing scandir-1.5-py2.7-win32.egg
scandir 1.5 is already the active version in easy-install.pth

Using c:\users\jshapir1\downloads\pythontemp\env\lib\site-packages\scandir-1.5-py2.7-win32.egg
Searching for requests==2.18.4
Best match: requests 2.18.4
Adding requests 2.18.4 to easy-install.pth file

Using c:\users\jshapir1\downloads\pythontemp\env\lib\site-packages
Searching for idna==2.6
Best match: idna 2.6
Adding idna 2.6 to easy-install.pth file

Using c:\users\jshapir1\downloads\pythontemp\env\lib\site-packages
Searching for urllib3==1.22
Best match: urllib3 1.22
Adding urllib3 1.22 to easy-install.pth file

Using c:\users\jshapir1\downloads\pythontemp\env\lib\site-packages
Searching for certifi==2017.7.27.1
Best match: certifi 2017.7.27.1
Adding certifi 2017.7.27.1 to easy-install.pth file

Using c:\users\jshapir1\downloads\pythontemp\env\lib\site-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect-script.py script to C:\Users\jshapir1\Downloads\pythontemp\env\Scripts
Installing chardetect.exe script to C:\Users\jshapir1\Downloads\pythontemp\env\Scripts
Installing chardetect.exe.manifest script to C:\Users\jshapir1\Downloads\pythontemp\env\Scripts

Using c:\users\jshapir1\downloads\pythontemp\env\lib\site-packages
Finished processing dependencies for GSLab-Tools==4.1.0
running clean
```
But when I run python in this virtualenv it doesn't see our packages:
```
~\Downloads\pythontemp> env/scripts/python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gslab_scons
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named gslab_scons
```
Any idea why? No need to spend a lot of time on this--just let me know if you see the issue.

**Comment by jmshapir** [comment]
On phone call we fixed the issue with installing gslab_python by running setup from inside the directory ```env/Scripts/gslab_python-4.1.0```.

We then used the virtualenv "activate" script to force all python commands (including scons) to use the virtualenv. We had to type ./activate rather than activate due to powershell security settings. Some discussion [here](env/Scripts/gslab_python-4.1.0).

That seemed to resolve everything up to some fiddliness with LyX.

**Comment by jmshapir** [comment]
I got the analysis directory working. 
I committed some results [here](https://github.com/gslab-econ/template/tree/4.1.0-jmstesting) just for illustration. The only remaining issue is a LyX crash that I'm pretty sure is unrelated to our tools.

@stanfordquan now that this is working, from your standpoint is the main thing left just for me to look it over to make sure I'm ok with the structure?

**Comment by stanfordquan** [comment]
Yes, thanks @jmshapir. You can also look through the release notes [here for template](https://github.com/gslab-econ/template/pull/85#issuecomment-327258103) and [here for `gslab_python`](https://github.com/gslab-econ/gslab_python/pull/125#issuecomment-328713637) to see if there's a feature you'd like to try out/comment on.

**Comment by jmshapir** [comment]
Great, thanks. I haven't tested the release protocol but everything else makes sense to me.
