### ISSUE TITLE
debrief error on new repo

### ISSUE THREAD

**Issue by lboxell** [gslab-econ/gslab_python#89]
@stanfordquan,

Do the `issue_size_warnings` in `scons_debrief` only get printed to the `state_of_repo.log`? If so, I think we might want to remove them. I think there are two issues with the current setup:
 (1) I think [this line](https://github.com/gslab-econ/gslab_python/blob/master/gslab_scons/size_warning.py#L63) causes issues on a repo that has been cloned, but doesn't have any version history yet.
 (2) I get errors if I don't have `/release/` as a folder. Though I don't understand why not having `/raw/` doesn't cause similar issues (see [here](https://github.com/gslab-econ/gslab_python/blob/master/gslab_scons/size_warning.py#L10)). 

Perhaps I'm missing something. 

I'm getting: 
```
scons: building terminated because of errors.
fatal: your current branch 'master' does not have any commits yet
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/leviboxell/anaconda/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Users/leviboxell/anaconda/lib/python2.7/site-packages/gslab_scons/misc.py", line 26, in scons_debrief
    issue_size_warnings(look_in, file_MB_limit, total_MB_limit)
  File "/Users/leviboxell/anaconda/lib/python2.7/site-packages/gslab_scons/size_warning.py", line 17, in issue_size_warnings
    versioned = create_size_dictionary(look_in)
  File "/Users/leviboxell/anaconda/lib/python2.7/site-packages/gslab_scons/size_warning.py", line 121, in create_size_dictionary
    raise ReleaseError("The path argument does not specify an "
ReleaseError: The path argument does not specify an existing directory.
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/Users/leviboxell/anaconda/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Users/leviboxell/anaconda/lib/python2.7/site-packages/gslab_scons/misc.py", line 26, in scons_debrief
    issue_size_warnings(look_in, file_MB_limit, total_MB_limit)
  File "/Users/leviboxell/anaconda/lib/python2.7/site-packages/gslab_scons/size_warning.py", line 17, in issue_size_warnings
    versioned = create_size_dictionary(look_in)
  File "/Users/leviboxell/anaconda/lib/python2.7/site-packages/gslab_scons/size_warning.py", line 121, in create_size_dictionary
    raise ReleaseError("The path argument does not specify an "
gslab_scons._exception_classes.ReleaseError: The path argument does not specify an existing directory.
```

**Comment by lboxell** [comment]
(1)'s issue is actually [here](https://github.com/gslab-econ/gslab_python/blame/master/gslab_scons/misc.py#L37).

**Comment by lboxell** [comment]
For (1): We'll just add a try-except block and print 'No git version history' on failure.
For (2): We'll search for whether each folder in `lookin` exists before looking in it. If it doesn't, we just print a warning.

**Comment by lboxell** [comment]
Closing task.

Pull request: https://github.com/gslab-econ/gslab_python/pull/90

**Comment by lboxell** [comment]
Summary:
 - Fixed errors outlined in https://github.com/gslab-econ/gslab_python/issues/89#issue-246863522
 - Updated template to note versions 4.0.0 or later (see https://github.com/gslab-econ/template/commit/7229a9f8d6e4c6782aadeca0fa93973d9c5669df).
